---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.js
#
server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
monitoring.ui.container.elasticsearch.enabled: true

## X-Pack security credentials
#
elasticsearch.username: ${ELASTIC_USERNAME}
elasticsearch.password: ${ELASTIC_PASSWORD}
xpack.security.enabled: true
xpack.encryptedSavedObjects.encryptionKey: "n8yPEMyhBTmhkAH5Vtv2qhsB7w5mZWKQ"
xpack.ingestManager.fleet.tlsCheckDisabled: true

xpack.ingestManager.fleet.kibana.host: "http://kibana:5601"
xpack.ingestManager.fleet.elasticsearch.host: "http://elasticsearch:9200"

