filebeat.inputs:
- type: log
  paths:
    - /usr/share/data/access.log
  index: "http_access_logs-filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
  processors:
    - add_tags:
        tags: ["access_combined_wcookie"]

output.logstash:
  hosts: ["logstash:5044"]

#output.console:
#  pretty: true
