version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: ${ELK_VERSION}
    environment:
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ES_JAVA_OPTS: "-Xmx${ES_HEAP} -Xms${ES_HEAP}"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: ${ELK_VERSION}
    environment:
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ELASTICSEARCH_HOST_PORT: elasticsearch:9200
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - elastic

  elastic-agent:
    build:
      context: elastic-agent/
      args:
        ELK_VERSION: ${ELK_VERSION}
    environment:
      FLEET_SETUP: 1
      FLEET_ENROLL: 1
      FLEET_ENROLL_INSECURE: 1
      KIBANA_HOST: http://kibana:5601
      KIBANA_USERNAME: ${ELASTIC_USERNAME}
      KIBANA_PASSWORD: ${ELASTIC_PASSWORD}
    volumes:
      - ./elastic-agent/data:/usr/share/data
    networks:
      - elastic


networks:
  elastic:
    driver: bridge
